/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as DiseaseAnalysisRouteImport } from './routes/disease-analysis'
import { Route as IngredientsRouteImport } from './routes/ingredients'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as SkinAnalysisRouteImport } from './routes/skin-analysis'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const DiseaseAnalysisRoute = DiseaseAnalysisRouteImport.update({
  id: '/disease-analysis',
  path: '/disease-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsRoute = IngredientsRouteImport.update({
  id: '/ingredients',
  path: '/ingredients',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const SkinAnalysisRoute = SkinAnalysisRouteImport.update({
  id: '/skin-analysis',
  path: '/skin-analysis',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/disease-analysis': typeof DiseaseAnalysisRoute
  '/ingredients': typeof IngredientsRoute
  '/progress': typeof ProgressRoute
  '/skin-analysis': typeof SkinAnalysisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/disease-analysis': typeof DiseaseAnalysisRoute
  '/ingredients': typeof IngredientsRoute
  '/progress': typeof ProgressRoute
  '/skin-analysis': typeof SkinAnalysisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/disease-analysis': typeof DiseaseAnalysisRoute
  '/ingredients': typeof IngredientsRoute
  '/progress': typeof ProgressRoute
  '/skin-analysis': typeof SkinAnalysisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/disease-analysis'
    | '/ingredients'
    | '/progress'
    | '/skin-analysis'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/disease-analysis'
    | '/ingredients'
    | '/progress'
    | '/skin-analysis'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/disease-analysis'
    | '/ingredients'
    | '/progress'
    | '/skin-analysis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  DiseaseAnalysisRoute: typeof DiseaseAnalysisRoute
  IngredientsRoute: typeof IngredientsRoute
  ProgressRoute: typeof ProgressRoute
  SkinAnalysisRoute: typeof SkinAnalysisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disease-analysis': {
      id: '/disease-analysis'
      path: '/disease-analysis'
      fullPath: '/disease-analysis'
      preLoaderRoute: typeof DiseaseAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients': {
      id: '/ingredients'
      path: '/ingredients'
      fullPath: '/ingredients'
      preLoaderRoute: typeof IngredientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skin-analysis': {
      id: '/skin-analysis'
      path: '/skin-analysis'
      fullPath: '/skin-analysis'
      preLoaderRoute: typeof SkinAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  DiseaseAnalysisRoute: DiseaseAnalysisRoute,
  IngredientsRoute: IngredientsRoute,
  ProgressRoute: ProgressRoute,
  SkinAnalysisRoute: SkinAnalysisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
